name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: verify
        uses: actions/checkout@v3

      - name: config
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build e publish
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fiap-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fiap-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: image docker
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/fiap-app:latest
          docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/fiap-app:latest
