name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: verify
        uses: actions/checkout@v3

      - name: config
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v2
        with:
          username: gu29adtr
          password: DockerFiap

      - name: build e publish
        run: |
          docker build -t gu29adtr/fiap-app:latest .
          docker push gu29adtr/fiap-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: login
        uses: docker/login-action@v2
        with:
          username: gu29adtr
          password: DockerFiap

      - name: image docker
        run: |
          docker pull gu29adtr/fiap-app:latest
          docker run -d -p 5000:5000 gu29adtr/fiap-app:latest
